homeassistant:
  name: Home
  latitude: 33.8822
  longitude: -84.3783
  elevation: 279
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customized

# Enables the frontend
frontend:

http:
  api_password: !env_var HA_UI_PASSWORD
  server_port: 8123
  ip_ban_enabled: True
  login_attempts_threshold: 10
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: moon
  - platform: yr
  - platform: time_date
    display_options:
      - 'date'
      - 'time'
  - platform: cpuspeed
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - visibility
      - humidity
      - temperature
  - platform: gtfs
    origin: 905889
    destination: 906647
    data: marta
  - platform: gtfs
    origin: 905890
    destination: 907766
    data: marta

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.200/24
    home_interval: 4

# Text to speech
tts:
  platform: google

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/home_assistant/ha_env/lib/python3.6/site-packages/libopenzwave-0.3.1-py3.6-linux-armv7l.egg/config

wemo:
  static:
    - 192.168.2.220

group:
  # Views
  general:
    name: General
    view: yes
    entities:
      - group.computer
      - group.date_time
      - group.yahoo_weather
  hosts:
    name: Hosts
    view: yes
    entities:
      - group.devices
  sensors:
    name: Sensors
    view: yes
    entities:
      - group.multi_sensor
      - group.power_strip_1
      - group.wifi_outlet_1
  other:
    name: Other
    view: yes
    entities:
      - group.multi_sensor_other
      - group.unused_switchs
      - group.unused_readings
      - group.power_strip_1_readings

  # Groups
  devices:
    name: Devices
    entities:
      - device_tracker.beast
      - device_tracker.yoga
      - device_tracker.mac
      - device_tracker.tv
      - device_tracker.asus_router
      - device_tracker.alpfstakem
      - device_tracker.wemo
      - device_tracker.androida306f1f411a403b0
      - device_tracker.broadlink_rmpropluse7eb86
      - device_tracker.routerasuscom
  yahoo_weather:
    name: Yahoo Weather
    entities:
      - sensor.yweather_condition
      - sensor.yweather_current
      - sensor.yweather_humidity
      - sensor.yweather_temperature
      - sensor.yweather_temperature_max
      - sensor.yweather_temperature_min
      - sensor.yweather_visibility
      - sensor.yweather_wind_speed
  wifi_outlet_1:
    name: Wifi Outlet 1
    entities:
      - switch.wemo_mini
  multi_sensor:
    name: MultiSensor
    entities:
      - binary_sensor.zmulti_1_sensor_4_0
      - sensor.zmulti_1_battery_level_4_0
      - sensor.zmulti_1_luminance_4_3
      - sensor.zmulti_1_relative_humidity_4_5
      - sensor.zmulti_1_temperature_4_1
  power_strip_1:
    name: Power Strip Z1
    entities:
      - switch.zstrip_1_switch_2_0
      - switch.zstrip_1_switch_2_0_2
      - switch.zstrip_1_switch_2_0_3
      - switch.zstrip_1_switch_2_0_4
      - switch.zstrip_1_switch_2_0_5
  power_strip_1_readings:
    name: Power Strip Z1 Readings
    entities:
      - sensor.zstrip_1_energy_2_0
      - sensor.zstrip_1_energy_2_0_2
      - sensor.zstrip_1_energy_2_0_3
      - sensor.zstrip_1_energy_2_0_4
      - sensor.zstrip_1_energy_2_0_5
      - sensor.zstrip_1_power_2_8
      - sensor.zstrip_1_power_2_8_2
      - sensor.zstrip_1_power_2_8_3
      - sensor.zstrip_1_power_2_8_4
      - sensor.zstrip_1_power_2_8_5
  computer:
    name: Computer
    entities:
      - sensor.cpu_speed
  date_time:
    name: Date Time
    entities:
      - sensor.date
      - sensor.time

automation: !include_dir_list automation/