# Upper right short press
alias: Switch 2 Toggle
hide_entity: False
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zmote_1_3
      scene_id: 3
action:
  - service: homeassistant.toggle
    entity_id: switch.zstrip_1_switch_2_0_3
