# Upper left long press
alias: Switch 1 Toggle
hide_entity: False
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zmote_1_3
      scene_id: 2
action:
  - service: homeassistant.toggle
    entity_id: switch.wemo_mini